version: '3.3'

services:
    api:
        build:
            context: ./
            dockerfile: ./api/Dockerfile
        container_name: api
        ports: 
            - 3000:3000
    front:
        build:
            context: ./
            dockerfile: ./front/Dockerfile
        container_name: front
        ports: 
            - 3001:3000
