apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: api
  template:
    metadata:
      name: api
      labels:
        app.kubernetes.io/name: api
    spec:
      containers:
        - name: api
          image: juliovcruz0/api
          ports:
            - containerPort: 3000
