apiVersion: apps/v1
kind: Deployment
metadata:
  name: front
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: front
  template:
    metadata:
      name: front
      labels:
        app.kubernetes.io/name: front
    spec:
      containers:
        - name: front
          image: juliovcruz0/front
          ports:
            - containerPort: 3000
